# -*- coding: utf-8 -*-
"""capstone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G4X1HOEcSVaDUMZSGnDKEB_zQ6w3J1sO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('fandango_scrape.csv')
df.head(8)

plt.figure(figsize=(12, 5), dpi=250)
sns.scatterplot(data=df, y='VOTES', x='RATING', hue='STARS')

# some test code
title = 'Jurassic World (2015)'
title.split('(')[-1].replace(')', '')

df['YEAR'] = df['FILM'].apply(
    lambda title: title.split('(')[-1].replace(')', ''))
df.head(10)

df['YEAR'].value_counts()

sns.countplot(df, x='YEAR')

# df.sort_values('VOTES',ascending= False)
df.nlargest(10, 'VOTES')

# how many movies have 0 votes
# no_votes = df['VOTES'] == 0
# no_votes.sum()
# or we can write
len(df[df['VOTES'] == 0])

reviewed = df[df['VOTES'] > 0]
reviewed

reviewed['REVIEW_DIFF'] = reviewed['STARS'] - reviewed['RATING']
reviewed

plt.figure(figsize=(30, 9), dpi=100)
sns.countplot(reviewed, x='REVIEW_DIFF')

reviewed[reviewed['REVIEW_DIFF'] == 1]
